mysite/clothes/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('item/<slug:item_slug>/', views.item_detail, name='item_detail'),
    path('category/<str:sex>/<str:category>/', views.category, name='category'),
    path('about', views.about, name='about'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('clothes/', include('clothes.urls')),
    path('admin/', admin.site.urls),
    path('', include('clothes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/clothes/models.py
from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal

class ProductManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)

def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)

class Item(models.Model):
    MATERIALS = (
        (None, 'прочее'),
        ('cotton', 'хлопок'),
        ('polyamide', 'полиамиды'),
        ('wool', 'шерсть'),
        ('polyester', 'полиэстеры'),
        ('silk', 'шелк'),
        ('velveteen', 'вельвет'),
        ('viscose', 'вискоза'),
        ('satin', 'сатин'),
    )

    SIZES = (
        (None, 'один размер'),
        ('xs', 'XS'),
        ('s', 'S'),
        ('m', 'M'),
        ('l', 'L'),
        ('xl', 'XL'),
        ('xxl', 'XXL'),
        ('xxxl', 'XXXL'),
    )

    GENDERS = (
        ('men', 'мужчинам'),
        ('women', 'женщинам'),
        ('unisex', 'унисекс'),
        ('kids', 'детям'),
    )

    CATEGORIES = (
        ('shirts', 'рубашки'),
        ('coats', 'пальто и куртки'),
        ('sweatshirts', 'толстовки'),
        ('blouses', 'блузки'),
        ('pullovers', 'полуверы'),
        ('tshirts', 'футболки'),
        ('trousers', 'штаны'),
        ('shorts', 'шорты'),
        ('dresses', 'платья'),
        ('skirts', 'юбки'),
        ('accessories', 'аксессуары'),
    )

    name = models.CharField(
        max_length=100,
        verbose_name='название')

    slug = models.SlugField(
        unique=True,
        default='',
        verbose_name='идентификатор'
    )

    description = models.TextField(
        null=True,
        blank=True,
        max_length=600,
        verbose_name='описание'
    )

    image = models.ImageField(
        upload_to=image_folder,
        default='/item_no_image.png',
        verbose_name='изображение'
    )

    material = models.CharField(
        null=True,
        blank=True,
        max_length=10,
        choices=MATERIALS,
        default=None,
        verbose_name='материал'
    )

    price = models.DecimalField(
        decimal_places=0,
        max_digits=12,
        validators=[MinValueValidator(Decimal('0.01'))],
        verbose_name='стоимость'
    )

    size = models.CharField(
        null=True,
        blank=True,
        max_length=11,
        choices=SIZES,
        default='m',
        verbose_name='размер'
    )

    gender = models.CharField(
        null=True,
        blank=True,
        max_length=8,
        choices=GENDERS,
        default=None,
        verbose_name='пол'
    )

    category = models.CharField(
        null=True,
        blank=True,
        max_length=15,
        choices=CATEGORIES,
        default=None,
        verbose_name='категория'
    )

    available = models.BooleanField(
        default=True,
        verbose_name='в наличии'
    )

    objects = ProductManager()

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        super(Item, self).delete(*args, **kwargs)

mysite/clothes/views.py
from operator import itemgetter

from django.shortcuts import get_object_or_404, render
from .models import Item

from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse
from django.views import generic
from django.utils import timezone

def index(request):
    categories = Item.CATEGORIES
    items = Item.objects.all()
    context = {
        'categories': categories,
        'items': items,
    }
    return render(request, 'clothes/index.html', context)

def item_detail(request, item_slug):
    item = Item.objects.get(slug=item_slug)
    context = {
        'item': item,
    }
    return render(request, 'clothes/item.html', context)


def category(request, sex, category):
    items = Item.objects.all()

    if sex != 'anygender':
        if sex == 'women':
            items = items.filter(gender__in=['women', 'unisex'])
        if sex == 'men':
            items = items.filter(gender__in=['men', 'unisex'])
        if sex == 'kids':
            items = items.filter(gender__in=['kids'])

    if category != 'all':
        if category in map(itemgetter(0), Item.CATEGORIES):
            items = items.filter(category=category)
        else:
            if category == 'tops':
                items = items.filter(category__in=['shirts', 'coats', 'sweatshirts', 'blouses', 'pullovers', 'tshirts'])
            if category == 'bottoms':
                items = items.filter(category__in=['trousers', 'shorts', 'skirts'])

    context = {
        'gender': sex,
        'category': category,
        'items': items,
    }

    return render(request, 'clothes/category.html', context)

def about(request):
    return render(request, 'clothes/about.html', {})

mysite/clothes/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">

    <title>{% block title %}СЛОН-ОРИГИНАЛ{% endblock title %}</title>
    <link rel="shortcut icon" href="https://www.iconsdb.com/icons/preview/deep-pink/elephant-xxl.png" type="image/png" />

    {% load static %}
    {% load bootstrap4 %}

    <script src="{% bootstrap_jquery_url %}"></script>
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'clothes/footer.css' %}">

    {% block custom_static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'clothes/style.css' %}">
    {% endblock custom_static%}
</head>

<body>
    <div id="page-container">
        <div id="content-wrap">

            {% block main_brand %}
            <p class="text-center my-4" style="font-size: 50px; font-family: SimSun;">
                <h1 style="text-align: center;">
                    <a class="main_title" href="/">СЛОН-ОРИГИНАЛ</a>
                </h1>

                <h5 style="text-align: center;">
                    <a class="main_title" href="/about">сэконд и сток</a>
                </h5>      
            </p>
            {% endblock main_brand %}

            <!-- навигация -->
            {% block navigation_bar %}
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>

            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

            <nav class="navbar navbar-expand-md bg-light navbar-light sticky-top">
                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                    <!-- брэнд -->
                    <ul class="navbar-nav mr-auto navbar-left">

                        <!-- dropdown women -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop_women" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                женщины
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/category/women/all/">всё</a>
                                <a class="dropdown-item" href="/category/women/tops/">верх</a>
                                <a class="dropdown-item" href="/category/women/bottoms/">низ</a>
                                <a class="dropdown-item" href="/category/women/accessories/">аксессуары</a>
                                <a class="dropdown-item" href="/category/women/dresses/">платья</a>
                            </div>
                        </li>

                        <!-- dropdown men -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop_men" data-toggle="dropdown">
                                мужчины
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/category/men/all/">всё</a>
                                <a class="dropdown-item" href="/category/men/tops/">верх</a>
                                <a class="dropdown-item" href="/category/men/bottoms/">низ</a>
                                <a class="dropdown-item" href="/category/men/accessories/">аксессуары</a>
                            </div>
                        </li>

                        <!-- dropdown kids -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop_kids" data-toggle="dropdown">
                                дети
                            </a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/category/kids/all/">всё</a>
                                <a class="dropdown-item" href="/category/kids/tops/">верх</a>
                                <a class="dropdown-item" href="/category/kids/bottoms/">низ</a>
                                <a class="dropdown-item" href="/category/kids/accessories/">аксессуары</a>
                            </div>
                        </li>

                        <!-- link accessories -->
                        <li class="nav-item">
                            <a class="nav-link" href="/category/anygender/accessories/" id="navbardrop_accessories">аксессуары</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                    </ul>
                </div>

                <!-- brand at the navbar center -->
                    <!--    <div class="mx-auto order-0">
                            <a class="navbar-brand mx-auto" href="#">Navbar 2</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>-->
            </nav>
            {% endblock navigation_bar %}
            
            <div class="container">
            {% block content %}
            {% endblock content%}
            </div>
        </div>

        <footer id="footer">
            <hr>
            <div class="container bg-light">
                <p class="copyright">
                    &copy; Слон-Оригинал · 
                    <a href="/about">о магазине</a>
                </p>
            </div>
        </footer>
    </div>
</body>
</html>

mysite/clothes/templates/base_about.html
{% extends 'base.html' %}

<!-- навигация -->
{% block navigation_bar %}
<hr>
{% endblock navigation_bar %}

{% block title %}СЛОН-ОРИГИНАЛ | о магазине{% endblock title %}

mysite/clothes/templates/base_category.html
{% extends 'base.html' %}

{% block title %}СЛОН-ОРИГИНАЛ | раздел{% endblock title %}

mysite/clothes/templates/base_homepage.html
{% extends 'base.html' %}

{% block title %}СЛОН-ОРИГИНАЛ | С 2019{% endblock title %}

mysite/clothes/templates/base_item.html
{% extends 'base.html' %}

{% block title %}{{ item.name }} | СЛОН-ОРИГИНАЛ{% endblock title %}

mysite/clothes/templates/clothes/Product.html
<div id="content">
  <div class="top">
    <div class="left"></div>
    <div class="right"></div>
    <div class="center">
      <h1>{{ product.title }}</h1>
    </div>
  </div>

  <div class="middle hproduct">
    <div style="width: 100%; margin-bottom: 30px;">
      <table style="width: 50%; border-collapse: collapse;">
        <tbody>
          <tr>
            
            <td style="text-align: left; width: 1px; vertical-align: top;">
              <img src="{{  }}" title="{{ product.title }}" alt="{{ product.title }}"
                   id="image" class="photo" style="margin-bottom: 3px; width: 250px; height: 250px;"> <!-- как мы получаем картинку? -->
              </a>
            </td>

            <td style="padding-left: 15px; width: 296px; vertical-align: top;">
              <table width="100%">
                <tbody>
                  <tr>
                    <td><b>{% "Model" %}:</b></td>
                    <td class="">{{ product.title }}</td>
                  </tr>
                  
                  <tr>
                    <td><b>{%  "Price" %}:</b></td>
                    <td class="">{{ product.price|floatformat:2 }}&nbsp;р.</td>
                  </tr>                  
                  
                  <tr>
                    <td><b>{% "Size" %}:</b></td>
                    <td class="">{{ product.size }}</td>
                  </tr>
                  
                  <tr>
                    <td><b>{% "Description" %}:</b></td>
                    <td class="">{{ product.description }}</td>
                  </tr>       
			           </tbody>
              </table>
              
              <br/>
              
              </div>
              </form>
              
            </td>
          </tr>
        </tbody>
      </table>
    </div> 
  </div>
</div>
{% endblock %}

mysite/clothes/templates/clothes/about.html
{% extends 'base_about.html' %}

{% block content %}
<div class="row">
	<div class="col-sm-12 ">
	   	<h3 class="text-center">{{item.name}}</h3>
	  	<p>{{ item.description }}</p>
	   	
	   	<p>	САМАЯ ВАЖНАЯ ИНФОРМАЦИЯ:<br>
			— чтобы заказать или спросить, что угодно пишите МНЕ;<br>
			— доставка по Москве в пределах метро БЕСПЛАТНО, по России — 300 рублей;<br>
			— при покупке от 900 рублей ЭКСКЛЮЗИВНЫЙ СТИКЕРПАК В ПОДАРОК;<br>
			— при покупке от 3 вещей ЧЕТВЁРТАЯ В ПОДАРОК.<br>
			<br>
			Лучший интернет-сэконд за последнюю тысячу лет реализует:<br>
			— принципы разумного потребления;<br>
			— ваше желание быть стильным и изысканным;<br>
			— уважение к слонам.<br>
			<br>
			Добро пожаловать! :3
		</p>
	   	<p></p>
	</div>
</div>
{% endblock content %}

mysite/clothes/templates/clothes/category.html
{% extends 'base_category.html' %}

{% block content %}

{% if category == "all"  %}
<h1 align="center">всё</h1>
{% elif category == "tops" %}
<h1 align="center">верх</h1>
{% elif category == "bottoms" %}
<h1 align="center">низ</h1>
{% elif category == "dresses" %}
<h1 align="center">платья</h1>
{% elif category == "accessories" %}
<h1 align="center">аксессуары</h1>
{% endif %}

<!-- item cards -->
<div class="row">
    
    {% for item in items reversed %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="/item/{{ item.slug }}">
                <img class="card-img-top" src="{{ item.image.url }}" alt=""
                     style="width: 100%; max-height: 350px;">
            </a>
            <div class="card-body">
                <h4 class="card-title" style="text-align: center;">
                    <a href="/item/{{ item.slug }}">{{ item.name }}</a>
                </h4>

                <h5 style="text-align: center;">{{ item.price }} &#8381</h5>                
            </div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock content %}

mysite/clothes/templates/clothes/index.html
{% extends 'base_homepage.html' %}

{% block content %}

<!--  carousel -->
<br>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        
        <div class="carousel-item active">
            <img class="d-block w-100" src="https://standon-calling.com/wp-content/uploads/2019/02/COMEDYTRIM-2-1080x500.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Большой выбор одежды</h5>
                <p>Широкий ассортимент разнообразных товаров на разные сезоны.  </p>
            </div>
        </div>

        <div class="carousel-item">
            <img class="d-block w-100" src="http://onefake.ru/wp-content/uploads/2017/03/P3040002-1080x500.jpg" alt="Second slide">
             <div class="carousel-caption d-none d-md-block">
                <h5>Зарубежные бренды</h5>
                <p>Одежда поступает из-за границы без посредников</p>
            </div>
        </div>
        
        <div class="carousel-item">
            <img class="d-block w-100" src="http://onefake.ru/wp-content/uploads/2017/03/P2132510-1080x500.jpg" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Качественное отношение к товару</h5>
                <p>Каждый товар лично проверяется продавцом перед продажей.</p>
            </div>
        </div>

    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>

</div>

<!-- end of carousel -->

<br>
    <p class="text-center my-4" style="font-size: 30px;">
        новые поступления
    </p>
<hr>

<!-- карточки item -->
<div class="row">
    {% for item in items  reversed%}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <a href="/item/{{ item.slug }}">
                <img    class="card-img-top" 
                        src="{{ item.image.url }}" alt=""
                        style="width: 100%; max-height: 350px;">
            </a>

            <div class="card-body">
                <h4 class="card-title" style="text-align: center;">
                    <a href="/item/{{ item.slug }}">{{ item.name | truncatechars:50 }}</a>
                </h4>
                <h5 style="text-align: center;">{{ item.price | truncatechars:50 }} &#8381</h5>
            </div>

        </div>
    </div>
    {% endfor %}

</div>
{% endblock content %}

mysite/clothes/templates/clothes/item.html
{% extends 'base_item.html' %}

{% block content %}
<div class="row" style="margin-top: 30px">
    
    <div class="col-sm-4 my-3">
        <p style="text-align: center;">
            <img src="{{ item.image.url }}" style=" width: 80%; height: 250px">
        </p>

        <p style="text-align: center;">
            цена &middot {{item.price}} &#8381<br>
            материал &middot {{item.get_material_display}}<br>
            размер &middot {{item.get_size_display}}<br>
        </p>
    </div>

    <div class="col-sm-8 ">
        <h3 class="text-center">{{item.name}}</h3>
        <hr>
        <p>{{ item.description }}</p>
        <hr>
    </div>
</div>
{% endblock content %}